apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tcsdevops2
spec: 
  replicas: 1
  template:
    metadata:
      labels:
        name: tcsdevops2
    spec:
      containers: 
      - name: tcsdevops2
        image: gcr.io/tcsdevopsathon/myfinaltcsdevopsss:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
